### PR TITLE
Add Text-Runner as project that uses this library

### PR DESCRIPTION
**Pull request by kevgo**
Thanks for creating this library!

### CODE REVIEW

**Review by IonicaBizau — APPROVED** [review]

**Comment by IonicaBizau** [comment]
That list is generated. I'm not sure if when I will generate `README.md` next time it will still remain there (because you are using it as a dev dependency).

Merging for now. Thanks! :)

**Comment by kevgo** [comment]
I think you should include dev dependencies into your generated list, if that is possible.

**Comment by IonicaBizau** [comment]
I agree. I'm not sure if `npm` does that or not.

However, a reason could be that [text-runner](https://www.npmjs.com/package/text-runner) was published 6 months ago, without depending on `class-methods`.

**Comment by kevgo** [comment]
I see. I have just added your library, and haven't published a new version containing it to NPM. I will do that in the next couple of weeks.

**Pull request merged**
